### ISSUE TITLE
how to generate images with a specified label

### ISSUE THREAD

**Issue by wqingzex** [AlexiaJM/AdversarialConsistentScoreMatching#1]
if I understand correctly, the generated image with a random label in train dataset, so if I want to generate some images with a specified label, how can I do that, every class label has their own model?

**Comment by AlexiaJM** [comment]
https://openreview.net/forum?id=PxTIG12RRHS provides a way through a classifier but that looks pretty annoying to do since you need to trained a classifier conditional on sigma.

In my opinion, one simpler way would be to use the unconditional network (not conditional on time/sigma) but then make it conditional, but on the class. Change the models in https://github.com/ermongroup/ncsnv2/blob/master/models/ncsnv2.py to be conditional on class by taking inspiration from https://github.com/ermongroup/ncsnv2/blob/master/models/ncsn.py.

**Comment by wqingzex** [comment]
thanks，I will try it
